apiVersion: v1
kind: ConfigMap
metadata:
  name: me-add-two-config-file
data:
  endpoints.k8s.json: |
    {
      "me-add-one-uri": "me-add-one-service:5011"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: me-add-two-deployment
  labels:
    app: me-add-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: me-add-two
  template:
    metadata:
      labels:
        app: me-add-two
    spec:
      containers:
      - name: me-add-two-main
        image: me-add-two:{{ .Values.config.image_version }}
        imagePullPolicy: Never
        ports:
        - containerPort: 5012
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
        volumeMounts:
        - name: me-add-two-config
          mountPath: /app/config
      volumes:
      - name: me-add-two-config
        configMap:
          name: me-add-two-config-file
---
apiVersion: v1
kind: Service
metadata:
  name: me-add-two-service
spec:
  type: ClusterIP
  selector:
    app: me-add-two
  ports:
    - port: 5012